spring.profiles.active: local
server.error.include-message: always
logging.file.name: ./logs/Ud_todo-app.log
task.template.allowMultipleTasksFromTemplate: false
management:
  endpoints:
    web:
      base-path: /status

  metrics:
    enable:
      http: false

spring:
  resources:
    add-mappings: true